# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'armbicep'
  location: eastus
  rggroup: 'emailbest'
  
 

pool: 
  name: drk

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'armbicep'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create --name $(rggroup) --location "East US"'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'armbicep'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment group create --resource-group $(rggroup)  --template-file ./emailserv.bicep --parameters ./emailpara.json'
    
- task: AzureCLI@2
  inputs:
    azureSubscription: 'armbicep'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az network dns zone create -g $(rggroup) -n saponly.com'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'armbicep'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      touch ipoutput.txt
      az network public-ip show -g $(rggroup) -n ubuemail-ip  >> ipoutput.txt
- task: CmdLine@2
  inputs:
    script: 'cat ipoutput'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'armbicep'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az network dns record-set a add-record -g $(rggroup) -z saponly.com -n mail -a  $(ipAddress)'