# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'armbicep'
  location: eastus
  rggroup: 'emailbest'

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'armbicep'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment group create --resource-group rggroup  --template-file ./emailserv.bicep --parameters ./emailpara.json'
